export { default as ManagerMovie } from './ManagerMovie'
export { default as ManagerAccount } from './ManagerAccount'
export { default as ManagerShow } from './ManagerShow' 
export { default as ManagerRoom } from './ManagerRoom'
export { default as ManagerBill } from './ManagerBill'
export { default as Dashboard } from './Dashboard'